/**
 * New Template Expansion: 105+ templates for Menus, Invitations, Certificates
 * Uses programmatic Fabric.js JSON generation with varied color schemes and layouts
 */

function T(text, opts) {
  return {
    type: "textbox", version: "6.6.1", originX: "left", originY: "top",
    left: opts.left || 0, top: opts.top || 0, width: opts.width || 300, height: opts.height || 50,
    fill: opts.fill || "#000000", stroke: null, strokeWidth: 0,
    fontSize: opts.fontSize || 32, fontWeight: opts.fontWeight || "normal",
    fontFamily: opts.fontFamily || "Inter", fontStyle: opts.fontStyle || "normal",
    textAlign: opts.textAlign || "left", text, underline: opts.underline || false,
    linethrough: false, charSpacing: opts.charSpacing || 0, lineHeight: opts.lineHeight || 1.2,
    opacity: opts.opacity || 1, angle: 0, scaleX: 1, scaleY: 1,
  };
}

function R(opts) {
  return {
    type: "rect", version: "6.6.1", originX: "left", originY: "top",
    left: opts.left || 0, top: opts.top || 0, width: opts.width || 100, height: opts.height || 100,
    fill: opts.fill || "#6366f1", stroke: opts.stroke || null, strokeWidth: opts.strokeWidth || 0,
    rx: opts.rx || 0, ry: opts.ry || 0, opacity: opts.opacity || 1, angle: opts.angle || 0,
    scaleX: 1, scaleY: 1,
  };
}

function C(opts) {
  return {
    type: "circle", version: "6.6.1", originX: "left", originY: "top",
    left: opts.left || 0, top: opts.top || 0, radius: opts.radius || 50,
    fill: opts.fill || "#6366f1", stroke: opts.stroke || null, strokeWidth: opts.strokeWidth || 0,
    opacity: opts.opacity || 1, angle: 0, scaleX: 1, scaleY: 1,
  };
}

function L(opts) {
  return {
    type: "line", version: "6.6.1", originX: "left", originY: "top",
    left: opts.left || 0, top: opts.top || 0,
    x1: opts.x1 || 0, y1: opts.y1 || 0, x2: opts.x2 || 200, y2: opts.y2 || 0,
    stroke: opts.stroke || "#000000", strokeWidth: opts.strokeWidth || 2,
    fill: null, opacity: opts.opacity || 1, angle: 0, scaleX: 1, scaleY: 1,
  };
}

// ═══════════════════════════════════════════════════════════════
//  MENU TEMPLATES (36 designs)
// ═══════════════════════════════════════════════════════════════

export const menuTemplates = [
  // 1. Elegant Restaurant Menu
  {
    name: "Elegant Restaurant Menu",
    description: "Sophisticated fine dining menu with gold accents",
    category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300,
    tags: ["menu", "restaurant", "elegant", "fine-dining", "gold"],
    canvasData: { version: "6.6.1", background: "#1a1a1a", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#1a1a1a" }),
      R({ left: 100, top: 100, width: 2350, height: 3100, fill: "transparent", stroke: "#c9a84c", strokeWidth: 3 }),
      R({ left: 130, top: 130, width: 2290, height: 3040, fill: "transparent", stroke: "#c9a84c", strokeWidth: 1 }),
      T("✦", { left: 1175, top: 180, width: 200, fontSize: 48, fill: "#c9a84c", textAlign: "center", fontFamily: "serif" }),
      T("THE GOLDEN TABLE", { left: 300, top: 260, width: 1950, fontSize: 72, fontWeight: "bold", fill: "#c9a84c", textAlign: "center", fontFamily: "Playfair Display", charSpacing: 200 }),
      T("FINE DINING EXPERIENCE", { left: 300, top: 370, width: 1950, fontSize: 24, fill: "#a08030", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      R({ left: 1075, top: 440, width: 400, height: 2, fill: "#c9a84c" }),
      T("APPETIZERS", { left: 300, top: 520, width: 1950, fontSize: 32, fontWeight: "bold", fill: "#c9a84c", textAlign: "center", fontFamily: "Playfair Display", charSpacing: 300 }),
      T("Truffle Burrata  ·  Seared Foie Gras  ·  Tuna Tartare", { left: 300, top: 590, width: 1950, fontSize: 24, fill: "#d4d4d4", textAlign: "center", fontFamily: "Inter" }),
      T("Lobster Bisque  ·  Wagyu Carpaccio  ·  Oysters Rockefeller", { left: 300, top: 640, width: 1950, fontSize: 24, fill: "#d4d4d4", textAlign: "center", fontFamily: "Inter" }),
      T("$18 — $36", { left: 300, top: 700, width: 1950, fontSize: 20, fill: "#c9a84c", textAlign: "center", fontFamily: "Inter" }),
      R({ left: 1075, top: 770, width: 400, height: 1, fill: "#c9a84c", opacity: 0.5 }),
      T("ENTRÉES", { left: 300, top: 830, width: 1950, fontSize: 32, fontWeight: "bold", fill: "#c9a84c", textAlign: "center", fontFamily: "Playfair Display", charSpacing: 300 }),
      T("Pan-Seared Chilean Sea Bass .............. $48\nFiber Mignon with Truffle Jus .............. $62\nRack of Lamb Provençal .............. $56\nDuck Confit with Cherry Reduction .............. $44\nLobster Thermidor .............. $72", { left: 350, top: 900, width: 1850, fontSize: 26, fill: "#d4d4d4", fontFamily: "Inter", lineHeight: 1.8 }),
      R({ left: 1075, top: 1280, width: 400, height: 1, fill: "#c9a84c", opacity: 0.5 }),
      T("DESSERTS", { left: 300, top: 1340, width: 1950, fontSize: 32, fontWeight: "bold", fill: "#c9a84c", textAlign: "center", fontFamily: "Playfair Display", charSpacing: 300 }),
      T("Crème Brûlée  ·  Chocolate Soufflé  ·  Tiramisu\nPanna Cotta  ·  Tarte Tatin  ·  Affogato", { left: 300, top: 1410, width: 1950, fontSize: 24, fill: "#d4d4d4", textAlign: "center", fontFamily: "Inter", lineHeight: 1.6 }),
      T("$14 — $22", { left: 300, top: 1510, width: 1950, fontSize: 20, fill: "#c9a84c", textAlign: "center", fontFamily: "Inter" }),
    ]},
  },
  // 2. Modern Cafe Menu
  {
    name: "Modern Cafe Menu",
    description: "Clean minimalist cafe menu with warm tones",
    category: "menu", subcategory: "cafe",
    canvasWidth: 2550, canvasHeight: 3300,
    tags: ["menu", "cafe", "modern", "minimal", "coffee"],
    canvasData: { version: "6.6.1", background: "#faf7f2", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#faf7f2" }),
      R({ left: 0, top: 0, width: 2550, height: 600, fill: "#3d2b1f" }),
      T("☕", { left: 1125, top: 80, width: 300, fontSize: 80, textAlign: "center" }),
      T("BREW & BEAN", { left: 200, top: 220, width: 2150, fontSize: 80, fontWeight: "bold", fill: "#faf7f2", textAlign: "center", fontFamily: "Montserrat" }),
      T("ARTISAN COFFEE HOUSE", { left: 200, top: 340, width: 2150, fontSize: 22, fill: "#c4a882", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      R({ left: 1125, top: 420, width: 300, height: 2, fill: "#c4a882" }),
      T("COFFEE", { left: 200, top: 700, width: 1000, fontSize: 36, fontWeight: "bold", fill: "#3d2b1f", fontFamily: "Montserrat" }),
      T("Espresso ........................ $3.50\nAmericano ...................... $4.00\nCappuccino .................... $4.50\nLatte ............................. $5.00\nFlat White ....................... $4.75\nMocha ........................... $5.50\nCold Brew ....................... $5.00\nPour Over ....................... $5.50", { left: 200, top: 770, width: 1000, fontSize: 24, fill: "#5a4030", fontFamily: "Inter", lineHeight: 1.8 }),
      T("PASTRIES", { left: 1350, top: 700, width: 1000, fontSize: 36, fontWeight: "bold", fill: "#3d2b1f", fontFamily: "Montserrat" }),
      T("Croissant ...................... $3.50\nPain au Chocolat ............. $4.00\nBlueberry Muffin ............. $3.75\nCinnamon Roll ................. $4.50\nBanana Bread .................. $3.50\nScone ............................ $3.25\nDanish ........................... $4.00\nBrioche .......................... $3.75", { left: 1350, top: 770, width: 1000, fontSize: 24, fill: "#5a4030", fontFamily: "Inter", lineHeight: 1.8 }),
      R({ left: 200, top: 1350, width: 2150, height: 2, fill: "#3d2b1f", opacity: 0.2 }),
      T("SANDWICHES & BOWLS", { left: 200, top: 1420, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#3d2b1f", fontFamily: "Montserrat" }),
      T("Avocado Toast ................ $8.50    Acai Bowl ..................... $10.00\nCaprese Panini ................ $9.00    Grain Bowl .................... $11.00\nClub Sandwich ................. $9.50    Smoothie Bowl ............... $9.50", { left: 200, top: 1500, width: 2150, fontSize: 24, fill: "#5a4030", fontFamily: "Inter", lineHeight: 1.8 }),
    ]},
  },
  // 3. Italian Trattoria Menu
  {
    name: "Italian Trattoria Menu",
    description: "Rustic Italian restaurant menu with warm colors",
    category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300,
    tags: ["menu", "italian", "restaurant", "rustic", "trattoria"],
    canvasData: { version: "6.6.1", background: "#f5ebe0", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#f5ebe0" }),
      R({ left: 0, top: 0, width: 2550, height: 500, fill: "#8b0000" }),
      T("LA BELLA VITA", { left: 200, top: 120, width: 2150, fontSize: 90, fontWeight: "bold", fill: "#f5ebe0", textAlign: "center", fontFamily: "Playfair Display" }),
      T("TRATTORIA & PIZZERIA", { left: 200, top: 280, width: 2150, fontSize: 24, fill: "#e8c8a0", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("ANTIPASTI", { left: 200, top: 600, width: 2150, fontSize: 40, fontWeight: "bold", fill: "#8b0000", textAlign: "center", fontFamily: "Playfair Display" }),
      T("Bruschetta al Pomodoro .......... $12\nCaponata Siciliana .................. $14\nCarpaccio di Manzo ................ $16\nFritto Misto .......................... $15", { left: 400, top: 680, width: 1750, fontSize: 26, fill: "#4a3520", fontFamily: "Inter", lineHeight: 1.7 }),
      R({ left: 1075, top: 920, width: 400, height: 2, fill: "#8b0000", opacity: 0.4 }),
      T("PASTA", { left: 200, top: 970, width: 2150, fontSize: 40, fontWeight: "bold", fill: "#8b0000", textAlign: "center", fontFamily: "Playfair Display" }),
      T("Spaghetti Carbonara .............. $18\nPenne all'Arrabbiata ............... $16\nRisotto ai Funghi Porcini ......... $22\nLasagna della Nonna .............. $20\nGnocchi al Pesto .................... $19", { left: 400, top: 1050, width: 1750, fontSize: 26, fill: "#4a3520", fontFamily: "Inter", lineHeight: 1.7 }),
      R({ left: 1075, top: 1370, width: 400, height: 2, fill: "#8b0000", opacity: 0.4 }),
      T("PIZZA", { left: 200, top: 1420, width: 2150, fontSize: 40, fontWeight: "bold", fill: "#8b0000", textAlign: "center", fontFamily: "Playfair Display" }),
      T("Margherita .......................... $14\nDiavola ............................... $16\nQuattro Formaggi .................. $18\nProsciutto e Rucola ............... $17", { left: 400, top: 1500, width: 1750, fontSize: 26, fill: "#4a3520", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  // 4. Cocktail Bar Menu
  {
    name: "Cocktail Bar Menu",
    description: "Dark moody cocktail bar menu with neon accents",
    category: "menu", subcategory: "bar",
    canvasWidth: 2550, canvasHeight: 3300,
    tags: ["menu", "bar", "cocktail", "drinks", "nightlife"],
    canvasData: { version: "6.6.1", background: "#0d0d0d", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#0d0d0d" }),
      T("🍸", { left: 1100, top: 100, width: 350, fontSize: 100, textAlign: "center" }),
      T("THE VELVET LOUNGE", { left: 200, top: 280, width: 2150, fontSize: 64, fontWeight: "bold", fill: "#ff4081", textAlign: "center", fontFamily: "Montserrat" }),
      T("CRAFT COCKTAILS & SPIRITS", { left: 200, top: 380, width: 2150, fontSize: 20, fill: "#ff408180", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      R({ left: 200, top: 460, width: 2150, height: 1, fill: "#ff4081", opacity: 0.3 }),
      T("SIGNATURE COCKTAILS", { left: 200, top: 530, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#ff4081", fontFamily: "Montserrat" }),
      T("Velvet Sunset — Bourbon, blood orange, rosemary ........... $16\nMidnight Garden — Gin, elderflower, cucumber ................ $15\nSmoked Old Fashioned — Rye, maple, cherry .................. $18\nLavender Haze — Vodka, lavender, lemon ...................... $15\nDark & Stormy — Dark rum, ginger beer, lime ................ $14", { left: 200, top: 600, width: 2150, fontSize: 24, fill: "#cccccc", fontFamily: "Inter", lineHeight: 1.9 }),
      T("CLASSICS", { left: 200, top: 950, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#ff4081", fontFamily: "Montserrat" }),
      T("Martini — Gin or vodka, dry vermouth ........................ $14\nNegroni — Gin, Campari, sweet vermouth ...................... $14\nManhattan — Rye, sweet vermouth, bitters .................... $15\nDaiquiri — White rum, lime, simple syrup ..................... $13\nMojito — White rum, mint, lime, soda .......................... $13", { left: 200, top: 1020, width: 2150, fontSize: 24, fill: "#cccccc", fontFamily: "Inter", lineHeight: 1.9 }),
      T("WINE & BEER", { left: 200, top: 1370, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#ff4081", fontFamily: "Montserrat" }),
      T("House Red / White / Rosé ........... $12 / $14\nChampagne ................................ $18\nCraft Beer (rotating tap) ............... $8\nImported Lager ........................... $7", { left: 200, top: 1440, width: 2150, fontSize: 24, fill: "#cccccc", fontFamily: "Inter", lineHeight: 1.9 }),
    ]},
  },
  // 5. Sushi Menu
  {
    name: "Japanese Sushi Menu",
    description: "Minimalist Japanese sushi restaurant menu",
    category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300,
    tags: ["menu", "sushi", "japanese", "minimal", "asian"],
    canvasData: { version: "6.6.1", background: "#fefefe", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fefefe" }),
      R({ left: 0, top: 0, width: 80, height: 3300, fill: "#c41e3a" }),
      T("鮨", { left: 150, top: 150, width: 300, fontSize: 120, fill: "#c41e3a", fontFamily: "serif" }),
      T("SAKURA SUSHI", { left: 500, top: 180, width: 1800, fontSize: 64, fontWeight: "bold", fill: "#1a1a1a", fontFamily: "Montserrat" }),
      T("AUTHENTIC JAPANESE CUISINE", { left: 500, top: 280, width: 1800, fontSize: 20, fill: "#888888", fontFamily: "Inter", charSpacing: 300 }),
      R({ left: 500, top: 360, width: 200, height: 3, fill: "#c41e3a" }),
      T("NIGIRI", { left: 200, top: 450, width: 1000, fontSize: 36, fontWeight: "bold", fill: "#1a1a1a", fontFamily: "Montserrat" }),
      T("Salmon (Sake) ..................... $6\nTuna (Maguro) ..................... $7\nYellowtail (Hamachi) ............. $7\nShrimp (Ebi) ....................... $5\nEel (Unagi) ......................... $8\nOctopus (Tako) .................... $6", { left: 200, top: 520, width: 1000, fontSize: 24, fill: "#444444", fontFamily: "Inter", lineHeight: 1.8 }),
      T("ROLLS", { left: 1350, top: 450, width: 1000, fontSize: 36, fontWeight: "bold", fill: "#1a1a1a", fontFamily: "Montserrat" }),
      T("California Roll .................... $10\nSpicy Tuna Roll ................... $12\nDragon Roll ........................ $16\nRainbow Roll ....................... $18\nPhiladelphia Roll .................. $11\nTempura Shrimp Roll ............ $14", { left: 1350, top: 520, width: 1000, fontSize: 24, fill: "#444444", fontFamily: "Inter", lineHeight: 1.8 }),
      R({ left: 200, top: 1000, width: 2150, height: 1, fill: "#e0e0e0" }),
      T("SASHIMI PLATTERS", { left: 200, top: 1060, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#1a1a1a", fontFamily: "Montserrat" }),
      T("Chef's Selection (12 pcs) ......... $32    Deluxe Platter (18 pcs) ......... $48\nOmakase Experience ............... $65    Sashimi & Sake Pairing ......... $55", { left: 200, top: 1130, width: 2150, fontSize: 24, fill: "#444444", fontFamily: "Inter", lineHeight: 1.8 }),
    ]},
  },
  // 6. Brunch Menu
  {
    name: "Weekend Brunch Menu",
    description: "Bright and cheerful weekend brunch menu",
    category: "menu", subcategory: "brunch",
    canvasWidth: 2550, canvasHeight: 3300,
    tags: ["menu", "brunch", "breakfast", "weekend", "cheerful"],
    canvasData: { version: "6.6.1", background: "#fff8e7", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fff8e7" }),
      C({ left: 1800, top: -100, radius: 300, fill: "#fbbf24", opacity: 0.2 }),
      C({ left: -100, top: 2800, radius: 250, fill: "#fb923c", opacity: 0.15 }),
      T("GOOD MORNING", { left: 200, top: 200, width: 2150, fontSize: 28, fill: "#f59e0b", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      T("Sunday Brunch", { left: 200, top: 270, width: 2150, fontSize: 80, fontWeight: "bold", fill: "#92400e", textAlign: "center", fontFamily: "Playfair Display", fontStyle: "italic" }),
      R({ left: 1075, top: 400, width: 400, height: 3, fill: "#f59e0b" }),
      T("EGGS & CLASSICS", { left: 200, top: 500, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#92400e", fontFamily: "Montserrat" }),
      T("Eggs Benedict ........................ $14\nAvocado Toast ........................ $12\nFrench Toast .......................... $13\nPancake Stack ........................ $11\nOmelette (build your own) ........ $13\nShakshuka .............................. $14", { left: 200, top: 570, width: 2150, fontSize: 26, fill: "#78350f", fontFamily: "Inter", lineHeight: 1.7 }),
      T("BOWLS & HEALTHY", { left: 200, top: 960, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#92400e", fontFamily: "Montserrat" }),
      T("Acai Bowl .............................. $13\nGranola Parfait ....................... $10\nSmoothie Bowl ........................ $12\nChia Pudding .......................... $9\nQuinoa Breakfast Bowl ............. $14", { left: 200, top: 1030, width: 2150, fontSize: 26, fill: "#78350f", fontFamily: "Inter", lineHeight: 1.7 }),
      T("DRINKS", { left: 200, top: 1380, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#92400e", fontFamily: "Montserrat" }),
      T("Mimosa .............. $10    Bloody Mary ......... $12    Fresh Juice ........... $7\nCoffee ................ $4     Latte ................... $5     Matcha Latte ......... $6", { left: 200, top: 1450, width: 2150, fontSize: 26, fill: "#78350f", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  // 7. BBQ & Grill Menu
  {
    name: "BBQ & Smokehouse Menu",
    description: "Rustic barbecue smokehouse menu with wood textures",
    category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300,
    tags: ["menu", "bbq", "grill", "smokehouse", "rustic"],
    canvasData: { version: "6.6.1", background: "#2c1810", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#2c1810" }),
      R({ left: 100, top: 100, width: 2350, height: 3100, fill: "transparent", stroke: "#d4a574", strokeWidth: 2 }),
      T("🔥", { left: 1100, top: 150, width: 350, fontSize: 80, textAlign: "center" }),
      T("SMOKE & FIRE", { left: 200, top: 300, width: 2150, fontSize: 80, fontWeight: "bold", fill: "#d4a574", textAlign: "center", fontFamily: "Montserrat" }),
      T("PIT BBQ & SMOKEHOUSE", { left: 200, top: 420, width: 2150, fontSize: 22, fill: "#a07850", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      T("SMOKED MEATS", { left: 300, top: 570, width: 1950, fontSize: 36, fontWeight: "bold", fill: "#d4a574", fontFamily: "Montserrat" }),
      T("Brisket (per lb) ........................ $22\nPulled Pork (per lb) ................... $18\nSmoked Ribs (full rack) .............. $28\nSmoked Chicken (half) ............... $16\nSmoked Sausage Links ............... $14\nBurnt Ends .............................. $20", { left: 300, top: 640, width: 1950, fontSize: 26, fill: "#e8d5c0", fontFamily: "Inter", lineHeight: 1.8 }),
      R({ left: 1075, top: 1050, width: 400, height: 2, fill: "#d4a574", opacity: 0.4 }),
      T("SIDES", { left: 300, top: 1110, width: 1950, fontSize: 36, fontWeight: "bold", fill: "#d4a574", fontFamily: "Montserrat" }),
      T("Mac & Cheese ........... $6    Coleslaw .................. $5\nBaked Beans .............. $5    Cornbread ................ $4\nPotato Salad ............. $5    Collard Greens .......... $6", { left: 300, top: 1180, width: 1950, fontSize: 26, fill: "#e8d5c0", fontFamily: "Inter", lineHeight: 1.8 }),
      T("COMBO PLATTERS", { left: 300, top: 1440, width: 1950, fontSize: 36, fontWeight: "bold", fill: "#d4a574", fontFamily: "Montserrat" }),
      T("Pitmaster Special (3 meats + 2 sides) ........... $32\nFamily Feast (serves 4-6) ............................ $65\nSampler Platter (all meats + 3 sides) ............. $45", { left: 300, top: 1510, width: 1950, fontSize: 26, fill: "#e8d5c0", fontFamily: "Inter", lineHeight: 1.8 }),
    ]},
  },
  // 8. Vegan Menu
  {
    name: "Plant-Based Vegan Menu",
    description: "Fresh green vegan restaurant menu",
    category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300,
    tags: ["menu", "vegan", "plant-based", "healthy", "green"],
    canvasData: { version: "6.6.1", background: "#f0f7f0", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#f0f7f0" }),
      C({ left: 1800, top: -50, radius: 200, fill: "#22c55e", opacity: 0.1 }),
      T("🌱", { left: 1125, top: 120, width: 300, fontSize: 80, textAlign: "center" }),
      T("GREEN ROOTS", { left: 200, top: 260, width: 2150, fontSize: 72, fontWeight: "bold", fill: "#166534", textAlign: "center", fontFamily: "Montserrat" }),
      T("100% PLANT-BASED KITCHEN", { left: 200, top: 370, width: 2150, fontSize: 20, fill: "#4ade80", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      R({ left: 200, top: 440, width: 2150, height: 2, fill: "#22c55e", opacity: 0.3 }),
      T("STARTERS", { left: 200, top: 510, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#166534", fontFamily: "Montserrat" }),
      T("Crispy Cauliflower Bites ............ $10\nMushroom Ceviche ..................... $12\nSweet Potato Hummus ................ $9\nSpring Rolls (4 pcs) ................... $11", { left: 200, top: 580, width: 2150, fontSize: 26, fill: "#374151", fontFamily: "Inter", lineHeight: 1.7 }),
      T("MAINS", { left: 200, top: 900, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#166534", fontFamily: "Montserrat" }),
      T("Beyond Burger ........................ $16\nThai Coconut Curry ................... $15\nMediterranean Bowl .................. $14\nMushroom Risotto ..................... $17\nJackfruit Tacos (3) ................... $14\nStuffed Bell Peppers ................. $15", { left: 200, top: 970, width: 2150, fontSize: 26, fill: "#374151", fontFamily: "Inter", lineHeight: 1.7 }),
      T("DESSERTS", { left: 200, top: 1370, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#166534", fontFamily: "Montserrat" }),
      T("Raw Chocolate Cake ................. $10\nCoconut Ice Cream ................... $8\nFruit Sorbet Trio ...................... $9", { left: 200, top: 1440, width: 2150, fontSize: 26, fill: "#374151", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  // 9. Mexican Cantina Menu
  {
    name: "Mexican Cantina Menu",
    description: "Vibrant Mexican restaurant menu with bold colors",
    category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300,
    tags: ["menu", "mexican", "cantina", "vibrant", "tacos"],
    canvasData: { version: "6.6.1", background: "#fef3c7", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fef3c7" }),
      R({ left: 0, top: 0, width: 2550, height: 550, fill: "#dc2626" }),
      T("🌮", { left: 1100, top: 60, width: 350, fontSize: 80, textAlign: "center" }),
      T("EL FUEGO", { left: 200, top: 200, width: 2150, fontSize: 100, fontWeight: "bold", fill: "#fef3c7", textAlign: "center", fontFamily: "Montserrat" }),
      T("CANTINA & TAQUERIA", { left: 200, top: 360, width: 2150, fontSize: 24, fill: "#fca5a5", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("TACOS", { left: 200, top: 650, width: 1000, fontSize: 40, fontWeight: "bold", fill: "#dc2626", fontFamily: "Montserrat" }),
      T("Al Pastor ............... $4\nCarne Asada ........... $5\nCarnitas ................. $4\nChicken Tinga ......... $4\nFish (Baja style) ...... $5\nBirria ..................... $5", { left: 200, top: 720, width: 1000, fontSize: 26, fill: "#78350f", fontFamily: "Inter", lineHeight: 1.7 }),
      T("BURRITOS & BOWLS", { left: 1350, top: 650, width: 1000, fontSize: 40, fontWeight: "bold", fill: "#dc2626", fontFamily: "Montserrat" }),
      T("Classic Burrito ......... $12\nBowl (no tortilla) ...... $11\nSuper Burrito ........... $14\nVeggie Burrito ......... $11\nQuesadilla .............. $10\nChimichanga ........... $13", { left: 1350, top: 720, width: 1000, fontSize: 26, fill: "#78350f", fontFamily: "Inter", lineHeight: 1.7 }),
      R({ left: 200, top: 1200, width: 2150, height: 3, fill: "#dc2626", opacity: 0.3 }),
      T("DRINKS & MARGARITAS", { left: 200, top: 1270, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#dc2626", fontFamily: "Montserrat" }),
      T("Classic Margarita ........ $10    Paloma ..................... $10\nMichelada .................. $8     Horchata ................... $5\nJamaica ..................... $4     Mexican Coke ............. $3", { left: 200, top: 1340, width: 2150, fontSize: 26, fill: "#78350f", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  // 10. Dessert Menu
  {
    name: "Patisserie Dessert Menu",
    description: "Elegant French patisserie dessert menu",
    category: "menu", subcategory: "dessert",
    canvasWidth: 2550, canvasHeight: 3300,
    tags: ["menu", "dessert", "patisserie", "french", "sweet"],
    canvasData: { version: "6.6.1", background: "#fdf2f8", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fdf2f8" }),
      C({ left: 100, top: 100, radius: 150, fill: "#ec4899", opacity: 0.08 }),
      C({ left: 2000, top: 200, radius: 200, fill: "#f472b6", opacity: 0.06 }),
      T("MAISON SUCRÉE", { left: 200, top: 200, width: 2150, fontSize: 72, fontWeight: "bold", fill: "#831843", textAlign: "center", fontFamily: "Playfair Display" }),
      T("ARTISAN PATISSERIE", { left: 200, top: 310, width: 2150, fontSize: 22, fill: "#ec4899", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      R({ left: 1075, top: 380, width: 400, height: 2, fill: "#ec4899" }),
      T("SIGNATURE CAKES", { left: 200, top: 460, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#831843", fontFamily: "Montserrat" }),
      T("Opera Cake ............................ $9\nMille-Feuille ........................... $10\nParis-Brest ............................. $11\nTarte au Citron ....................... $9\nSaint-Honoré .......................... $12\nChocolate Fondant ................... $10", { left: 200, top: 530, width: 2150, fontSize: 26, fill: "#6b2150", fontFamily: "Inter", lineHeight: 1.7 }),
      T("MACARONS", { left: 200, top: 930, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#831843", fontFamily: "Montserrat" }),
      T("Single ............. $3    Box of 6 ........... $16    Box of 12 .......... $28\nFlavors: Raspberry, Pistachio, Vanilla, Chocolate, Lavender, Salted Caramel", { left: 200, top: 1000, width: 2150, fontSize: 26, fill: "#6b2150", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  // 11. Pizza Menu
  {
    name: "Artisan Pizza Menu",
    description: "Wood-fired artisan pizza menu with chalk style",
    category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300,
    tags: ["menu", "pizza", "artisan", "wood-fired", "chalk"],
    canvasData: { version: "6.6.1", background: "#1e1e1e", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#1e1e1e" }),
      T("🍕", { left: 1100, top: 100, width: 350, fontSize: 100, textAlign: "center" }),
      T("FIRE & DOUGH", { left: 200, top: 280, width: 2150, fontSize: 80, fontWeight: "bold", fill: "#ffffff", textAlign: "center", fontFamily: "Montserrat" }),
      T("WOOD-FIRED PIZZA", { left: 200, top: 400, width: 2150, fontSize: 22, fill: "#f97316", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      R({ left: 1075, top: 470, width: 400, height: 2, fill: "#f97316" }),
      T("CLASSIC PIZZAS", { left: 300, top: 550, width: 1950, fontSize: 36, fontWeight: "bold", fill: "#f97316", fontFamily: "Montserrat" }),
      T("Margherita — tomato, mozzarella, basil ..................... $14\nPepperoni — spicy pepperoni, mozzarella .................... $16\nQuattro Stagioni — artichoke, ham, mushroom, olive ..... $18\nDiavola — spicy salami, chili flakes ........................... $16\nCapricciosa — ham, mushroom, artichoke, olive ........... $17", { left: 300, top: 620, width: 1950, fontSize: 24, fill: "#e0e0e0", fontFamily: "Inter", lineHeight: 1.9 }),
      T("GOURMET PIZZAS", { left: 300, top: 1000, width: 1950, fontSize: 36, fontWeight: "bold", fill: "#f97316", fontFamily: "Montserrat" }),
      T("Truffle & Mushroom — truffle oil, porcini, fontina ....... $22\nFig & Prosciutto — fig jam, prosciutto, gorgonzola ........ $20\nSmoked Salmon — crème fraîche, capers, dill ............... $21\nBBQ Chicken — BBQ sauce, chicken, red onion ............ $18\nVegan Supreme — cashew cream, roasted vegetables .... $17", { left: 300, top: 1070, width: 1950, fontSize: 24, fill: "#e0e0e0", fontFamily: "Inter", lineHeight: 1.9 }),
    ]},
  },
  // 12. Seafood Menu
  {
    name: "Coastal Seafood Menu",
    description: "Fresh coastal seafood restaurant menu",
    category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300,
    tags: ["menu", "seafood", "coastal", "ocean", "fresh"],
    canvasData: { version: "6.6.1", background: "#f0f9ff", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#f0f9ff" }),
      R({ left: 0, top: 0, width: 2550, height: 500, fill: "#0c4a6e" }),
      T("THE ANCHOR", { left: 200, top: 140, width: 2150, fontSize: 80, fontWeight: "bold", fill: "#ffffff", textAlign: "center", fontFamily: "Montserrat" }),
      T("FRESH SEAFOOD & RAW BAR", { left: 200, top: 280, width: 2150, fontSize: 22, fill: "#7dd3fc", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("RAW BAR", { left: 200, top: 600, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#0c4a6e", fontFamily: "Montserrat" }),
      T("Oysters (half dozen) .................. $18\nShrimp Cocktail ........................ $16\nCeviche .................................. $14\nTuna Poke ............................... $15", { left: 200, top: 670, width: 2150, fontSize: 26, fill: "#334155", fontFamily: "Inter", lineHeight: 1.7 }),
      T("FROM THE SEA", { left: 200, top: 1000, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#0c4a6e", fontFamily: "Montserrat" }),
      T("Grilled Salmon ........................ $28\nLobster Tail ............................. $42\nFish & Chips ............................ $18\nSeared Scallops ....................... $32\nCrab Cakes .............................. $24\nClam Chowder ......................... $12", { left: 200, top: 1070, width: 2150, fontSize: 26, fill: "#334155", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  // 13-18: More menu variations (Thai, Indian, Steakhouse, Wine List, Brunch Cocktails, Bakery)
  {
    name: "Thai Street Food Menu", description: "Colorful Thai street food menu", category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "thai", "street-food", "asian", "spicy"],
    canvasData: { version: "6.6.1", background: "#fffbeb", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fffbeb" }),
      R({ left: 0, top: 0, width: 2550, height: 480, fill: "#ea580c" }),
      T("BANGKOK BITES", { left: 200, top: 120, width: 2150, fontSize: 80, fontWeight: "bold", fill: "#ffffff", textAlign: "center", fontFamily: "Montserrat" }),
      T("AUTHENTIC THAI STREET FOOD", { left: 200, top: 260, width: 2150, fontSize: 22, fill: "#fed7aa", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("NOODLES & RICE", { left: 200, top: 580, width: 1000, fontSize: 32, fontWeight: "bold", fill: "#ea580c", fontFamily: "Montserrat" }),
      T("Pad Thai .................. $14\nDrunken Noodles ........ $15\nKhao Pad .................. $12\nPad See Ew ............... $14\nBoat Noodles ............. $13", { left: 200, top: 650, width: 1000, fontSize: 26, fill: "#78350f", fontFamily: "Inter", lineHeight: 1.7 }),
      T("CURRIES", { left: 1350, top: 580, width: 1000, fontSize: 32, fontWeight: "bold", fill: "#ea580c", fontFamily: "Montserrat" }),
      T("Green Curry .............. $16\nRed Curry ................. $16\nMassaman Curry ......... $17\nPanang Curry ............. $16\nYellow Curry .............. $15", { left: 1350, top: 650, width: 1000, fontSize: 26, fill: "#78350f", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  {
    name: "Indian Spice Kitchen Menu", description: "Rich Indian restaurant menu with ornate details", category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "indian", "spice", "curry", "ornate"],
    canvasData: { version: "6.6.1", background: "#fef9e7", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fef9e7" }),
      R({ left: 0, top: 0, width: 2550, height: 500, fill: "#7c2d12" }),
      T("MAHARAJA'S TABLE", { left: 200, top: 130, width: 2150, fontSize: 72, fontWeight: "bold", fill: "#fbbf24", textAlign: "center", fontFamily: "Playfair Display" }),
      T("AUTHENTIC INDIAN CUISINE", { left: 200, top: 270, width: 2150, fontSize: 22, fill: "#fcd34d", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("APPETIZERS", { left: 200, top: 600, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#7c2d12", fontFamily: "Montserrat" }),
      T("Samosa (2 pcs) ............. $7    Pakora ...................... $8\nTandoori Wings ............ $12   Paneer Tikka .............. $11", { left: 200, top: 670, width: 2150, fontSize: 26, fill: "#451a03", fontFamily: "Inter", lineHeight: 1.7 }),
      T("CURRIES & MAINS", { left: 200, top: 870, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#7c2d12", fontFamily: "Montserrat" }),
      T("Butter Chicken ........................ $18\nTikka Masala ........................... $17\nPalak Paneer ........................... $15\nDal Makhani ............................ $14\nBiryani (Chicken/Lamb) ............. $19\nVindaloo ................................. $17", { left: 200, top: 940, width: 2150, fontSize: 26, fill: "#451a03", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  {
    name: "Premium Steakhouse Menu", description: "Luxury steakhouse menu with dark leather feel", category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "steakhouse", "premium", "luxury", "meat"],
    canvasData: { version: "6.6.1", background: "#1c1917", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#1c1917" }),
      R({ left: 100, top: 100, width: 2350, height: 3100, fill: "transparent", stroke: "#a16207", strokeWidth: 2 }),
      T("PRIME CUT", { left: 200, top: 200, width: 2150, fontSize: 90, fontWeight: "bold", fill: "#fbbf24", textAlign: "center", fontFamily: "Montserrat" }),
      T("STEAKHOUSE & GRILL", { left: 200, top: 340, width: 2150, fontSize: 22, fill: "#a16207", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      T("STEAKS", { left: 300, top: 500, width: 1950, fontSize: 36, fontWeight: "bold", fill: "#fbbf24", fontFamily: "Montserrat" }),
      T("Filet Mignon (8oz) ................... $52\nNew York Strip (12oz) ............... $48\nRibeye (14oz) .......................... $56\nPorterhouse (24oz) ................... $72\nWagyu A5 (4oz) ....................... $120\nT-Bone (16oz) .......................... $58", { left: 300, top: 570, width: 1950, fontSize: 26, fill: "#d6d3d1", fontFamily: "Inter", lineHeight: 1.8 }),
      T("All steaks served with choice of two sides", { left: 300, top: 960, width: 1950, fontSize: 20, fill: "#a8a29e", fontFamily: "Inter", fontStyle: "italic" }),
    ]},
  },
  {
    name: "Wine List Menu", description: "Sophisticated wine list for restaurants", category: "menu", subcategory: "bar",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "wine", "list", "elegant", "sommelier"],
    canvasData: { version: "6.6.1", background: "#1a0a1e", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#1a0a1e" }),
      T("🍷", { left: 1100, top: 100, width: 350, fontSize: 80, textAlign: "center" }),
      T("WINE LIST", { left: 200, top: 260, width: 2150, fontSize: 80, fontWeight: "bold", fill: "#c084fc", textAlign: "center", fontFamily: "Playfair Display" }),
      T("CURATED BY OUR SOMMELIER", { left: 200, top: 380, width: 2150, fontSize: 20, fill: "#a855f7", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      T("RED WINES", { left: 200, top: 530, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#c084fc", fontFamily: "Montserrat" }),
      T("Cabernet Sauvignon, Napa Valley ......... $14 / $52\nPinot Noir, Willamette Valley ............... $13 / $48\nMalbec, Mendoza ................................ $12 / $44\nBarolo, Piedmont ................................ $18 / $68", { left: 200, top: 600, width: 2150, fontSize: 24, fill: "#d4d4d4", fontFamily: "Inter", lineHeight: 1.8 }),
      T("WHITE WINES", { left: 200, top: 900, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#c084fc", fontFamily: "Montserrat" }),
      T("Chardonnay, Sonoma ........................ $12 / $44\nSauvignon Blanc, Marlborough ............. $11 / $40\nRiesling, Mosel ................................... $13 / $48\nPinot Grigio, Alto Adige ....................... $11 / $42", { left: 200, top: 970, width: 2150, fontSize: 24, fill: "#d4d4d4", fontFamily: "Inter", lineHeight: 1.8 }),
    ]},
  },
  {
    name: "Brunch Cocktails Menu", description: "Fun brunch cocktail menu with pastel colors", category: "menu", subcategory: "brunch",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "brunch", "cocktails", "mimosa", "pastel"],
    canvasData: { version: "6.6.1", background: "#fce7f3", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fce7f3" }),
      T("🥂", { left: 1100, top: 100, width: 350, fontSize: 80, textAlign: "center" }),
      T("BOTTOMLESS\nBRUNCH", { left: 200, top: 250, width: 2150, fontSize: 80, fontWeight: "bold", fill: "#831843", textAlign: "center", fontFamily: "Playfair Display", lineHeight: 1.1 }),
      T("$35 PER PERSON • 90 MINUTES", { left: 200, top: 480, width: 2150, fontSize: 24, fill: "#ec4899", textAlign: "center", fontFamily: "Inter", charSpacing: 200 }),
      R({ left: 1075, top: 550, width: 400, height: 3, fill: "#ec4899" }),
      T("COCKTAILS", { left: 200, top: 630, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#831843", textAlign: "center", fontFamily: "Montserrat" }),
      T("Classic Mimosa  ·  Peach Bellini  ·  Aperol Spritz\nBlood Orange Mimosa  ·  Lavender Lemonade\nRosé Sangria  ·  Elderflower Fizz  ·  Kir Royale", { left: 200, top: 710, width: 2150, fontSize: 28, fill: "#9d174d", textAlign: "center", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  {
    name: "Artisan Bakery Menu", description: "Warm artisan bakery menu with rustic charm", category: "menu", subcategory: "cafe",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "bakery", "artisan", "bread", "pastry"],
    canvasData: { version: "6.6.1", background: "#faf5ef", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#faf5ef" }),
      R({ left: 0, top: 0, width: 2550, height: 450, fill: "#78350f" }),
      T("THE FLOUR MILL", { left: 200, top: 120, width: 2150, fontSize: 72, fontWeight: "bold", fill: "#faf5ef", textAlign: "center", fontFamily: "Playfair Display" }),
      T("ARTISAN BAKERY & CAFE", { left: 200, top: 250, width: 2150, fontSize: 22, fill: "#d4a574", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("FRESH BREAD", { left: 200, top: 550, width: 1000, fontSize: 32, fontWeight: "bold", fill: "#78350f", fontFamily: "Montserrat" }),
      T("Sourdough Loaf ........... $7\nBaguette ..................... $5\nCiabatta ..................... $6\nRye Bread ................... $7\nFocaccia ..................... $8\nMultigrain ................... $7", { left: 200, top: 620, width: 1000, fontSize: 26, fill: "#451a03", fontFamily: "Inter", lineHeight: 1.7 }),
      T("PASTRIES", { left: 1350, top: 550, width: 1000, fontSize: 32, fontWeight: "bold", fill: "#78350f", fontFamily: "Montserrat" }),
      T("Croissant ................... $4\nPain au Chocolat ......... $4.50\nAlmond Croissant ........ $5\nDanish ....................... $4.50\nScone ........................ $3.50\nCinnamon Roll ............. $5", { left: 1350, top: 620, width: 1000, fontSize: 26, fill: "#451a03", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  // 19-24: Additional menu styles
  {
    name: "Taco Truck Menu", description: "Bold street taco truck menu board", category: "menu", subcategory: "restaurant",
    canvasWidth: 1920, canvasHeight: 1080, tags: ["menu", "taco", "truck", "street-food", "bold"],
    canvasData: { version: "6.6.1", background: "#fbbf24", objects: [
      R({ left: 0, top: 0, width: 1920, height: 1080, fill: "#fbbf24" }),
      T("TACO LOCO", { left: 100, top: 60, width: 800, fontSize: 80, fontWeight: "bold", fill: "#1a1a1a", fontFamily: "Montserrat" }),
      T("STREET TACOS", { left: 100, top: 170, width: 800, fontSize: 24, fill: "#78350f", fontFamily: "Inter", charSpacing: 300 }),
      T("Carne Asada ......... $4\nAl Pastor .............. $4\nCarnitas ............... $4\nChicken ............... $3.50\nFish .................... $5\nBirria .................. $5", { left: 100, top: 260, width: 700, fontSize: 28, fill: "#1a1a1a", fontFamily: "Inter", lineHeight: 1.6 }),
      T("SIDES & DRINKS", { left: 1000, top: 60, width: 800, fontSize: 36, fontWeight: "bold", fill: "#1a1a1a", fontFamily: "Montserrat" }),
      T("Rice & Beans ........ $3\nChips & Guac ........ $5\nElote ................... $4\nHorchata .............. $4\nJamaica ............... $3\nMexican Coke ....... $3", { left: 1000, top: 140, width: 800, fontSize: 28, fill: "#1a1a1a", fontFamily: "Inter", lineHeight: 1.6 }),
    ]},
  },
  {
    name: "Bubble Tea Menu", description: "Cute and colorful bubble tea menu", category: "menu", subcategory: "cafe",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "bubble-tea", "boba", "cute", "colorful"],
    canvasData: { version: "6.6.1", background: "#fdf4ff", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fdf4ff" }),
      C({ left: 100, top: 100, radius: 200, fill: "#d946ef", opacity: 0.1 }),
      C({ left: 2000, top: 300, radius: 150, fill: "#a855f7", opacity: 0.1 }),
      T("🧋", { left: 1100, top: 100, width: 350, fontSize: 100, textAlign: "center" }),
      T("BOBA BLISS", { left: 200, top: 280, width: 2150, fontSize: 80, fontWeight: "bold", fill: "#7e22ce", textAlign: "center", fontFamily: "Montserrat" }),
      T("MILK TEAS", { left: 200, top: 480, width: 1000, fontSize: 36, fontWeight: "bold", fill: "#7e22ce", fontFamily: "Montserrat" }),
      T("Classic Milk Tea ......... $6\nTaro Milk Tea ............. $6.50\nMatcha Latte .............. $7\nBrown Sugar .............. $7\nStrawberry ................. $6.50\nOolong ...................... $6", { left: 200, top: 550, width: 1000, fontSize: 26, fill: "#581c87", fontFamily: "Inter", lineHeight: 1.7 }),
      T("FRUIT TEAS", { left: 1350, top: 480, width: 1000, fontSize: 36, fontWeight: "bold", fill: "#7e22ce", fontFamily: "Montserrat" }),
      T("Passion Fruit ............. $6\nMango Green Tea ....... $6.50\nLychee Rose .............. $7\nPeach Oolong ............ $6.50\nWatermelon ............... $6\nYuzu Citrus ............... $6.50", { left: 1350, top: 550, width: 1000, fontSize: 26, fill: "#581c87", fontFamily: "Inter", lineHeight: 1.7 }),
      T("TOPPINGS: +$0.75 each", { left: 200, top: 1000, width: 2150, fontSize: 24, fontWeight: "bold", fill: "#7e22ce", textAlign: "center", fontFamily: "Inter" }),
      T("Tapioca Pearls  ·  Jelly  ·  Pudding  ·  Aloe Vera  ·  Coconut  ·  Red Bean", { left: 200, top: 1060, width: 2150, fontSize: 22, fill: "#581c87", textAlign: "center", fontFamily: "Inter" }),
    ]},
  },
  {
    name: "Ice Cream Parlor Menu", description: "Fun retro ice cream parlor menu", category: "menu", subcategory: "dessert",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "ice-cream", "parlor", "retro", "fun"],
    canvasData: { version: "6.6.1", background: "#e0f2fe", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#e0f2fe" }),
      T("🍦", { left: 1100, top: 80, width: 350, fontSize: 100, textAlign: "center" }),
      T("SCOOPS!", { left: 200, top: 250, width: 2150, fontSize: 100, fontWeight: "bold", fill: "#0369a1", textAlign: "center", fontFamily: "Montserrat" }),
      T("ICE CREAM PARLOR", { left: 200, top: 390, width: 2150, fontSize: 24, fill: "#0284c7", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("FLAVORS", { left: 200, top: 520, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#0369a1", textAlign: "center", fontFamily: "Montserrat" }),
      T("Vanilla Bean  ·  Chocolate Fudge  ·  Strawberry\nMint Chip  ·  Cookie Dough  ·  Salted Caramel\nPistachio  ·  Mango Sorbet  ·  Coffee\nRaspberry Ripple  ·  Cookies & Cream  ·  Matcha", { left: 200, top: 590, width: 2150, fontSize: 26, fill: "#1e3a5f", textAlign: "center", fontFamily: "Inter", lineHeight: 1.7 }),
      T("Single .... $4    Double .... $6    Triple .... $8    Waffle Cone .... +$1.50", { left: 200, top: 870, width: 2150, fontSize: 24, fontWeight: "bold", fill: "#0369a1", textAlign: "center", fontFamily: "Inter" }),
    ]},
  },
  {
    name: "Ramen Shop Menu", description: "Japanese ramen shop menu with bold typography", category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "ramen", "japanese", "noodles", "bold"],
    canvasData: { version: "6.6.1", background: "#fef2f2", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fef2f2" }),
      R({ left: 0, top: 0, width: 2550, height: 500, fill: "#dc2626" }),
      T("麺", { left: 200, top: 80, width: 300, fontSize: 120, fill: "#ffffff", fontFamily: "serif" }),
      T("ICHIBAN RAMEN", { left: 550, top: 140, width: 1800, fontSize: 72, fontWeight: "bold", fill: "#ffffff", fontFamily: "Montserrat" }),
      T("AUTHENTIC JAPANESE NOODLES", { left: 550, top: 280, width: 1800, fontSize: 22, fill: "#fca5a5", fontFamily: "Inter", charSpacing: 300 }),
      T("RAMEN", { left: 200, top: 600, width: 2150, fontSize: 40, fontWeight: "bold", fill: "#dc2626", fontFamily: "Montserrat" }),
      T("Tonkotsu (pork bone broth) ............... $16\nShoyu (soy sauce broth) .................... $15\nMiso (fermented soybean broth) .......... $16\nShio (salt broth) ............................... $15\nTantanmen (spicy sesame) .................. $17\nTsukemen (dipping noodles) ............... $17", { left: 200, top: 680, width: 2150, fontSize: 26, fill: "#1f2937", fontFamily: "Inter", lineHeight: 1.8 }),
      T("SIDES", { left: 200, top: 1100, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#dc2626", fontFamily: "Montserrat" }),
      T("Gyoza (6 pcs) .......... $8    Karaage .................. $10\nEdamame ................. $5    Extra Chashu ........... $4\nRice ........................ $3    Soft-Boiled Egg ........ $2", { left: 200, top: 1170, width: 2150, fontSize: 26, fill: "#1f2937", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  {
    name: "Food Truck Festival Menu", description: "Colorful food truck festival menu board", category: "menu", subcategory: "restaurant",
    canvasWidth: 1920, canvasHeight: 1080, tags: ["menu", "food-truck", "festival", "colorful", "street"],
    canvasData: { version: "6.6.1", background: "#18181b", objects: [
      R({ left: 0, top: 0, width: 1920, height: 1080, fill: "#18181b" }),
      R({ left: 0, top: 0, width: 640, height: 1080, fill: "#dc2626" }),
      R({ left: 640, top: 0, width: 640, height: 1080, fill: "#f59e0b" }),
      R({ left: 1280, top: 0, width: 640, height: 1080, fill: "#22c55e" }),
      T("BURGERS", { left: 80, top: 60, width: 480, fontSize: 40, fontWeight: "bold", fill: "#ffffff", textAlign: "center", fontFamily: "Montserrat" }),
      T("Classic ........... $10\nCheese ............ $11\nBBQ Bacon ....... $13\nMushroom ........ $12\nVeggie ............. $10", { left: 80, top: 140, width: 480, fontSize: 24, fill: "#fecaca", textAlign: "center", fontFamily: "Inter", lineHeight: 1.7 }),
      T("TACOS", { left: 720, top: 60, width: 480, fontSize: 40, fontWeight: "bold", fill: "#1a1a1a", textAlign: "center", fontFamily: "Montserrat" }),
      T("Carne Asada ..... $4\nAl Pastor ........... $4\nFish .................. $5\nChicken ............. $3.50\nVeggie .............. $3.50", { left: 720, top: 140, width: 480, fontSize: 24, fill: "#451a03", textAlign: "center", fontFamily: "Inter", lineHeight: 1.7 }),
      T("BOWLS", { left: 1360, top: 60, width: 480, fontSize: 40, fontWeight: "bold", fill: "#ffffff", textAlign: "center", fontFamily: "Montserrat" }),
      T("Poke Bowl ........ $14\nAcai Bowl .......... $12\nGrain Bowl ........ $13\nBurrito Bowl ...... $12\nSalad Bowl ........ $11", { left: 1360, top: 140, width: 480, fontSize: 24, fill: "#dcfce7", textAlign: "center", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  // 24-30: More specialized menus
  {
    name: "Dim Sum Menu", description: "Traditional Chinese dim sum menu", category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "dim-sum", "chinese", "traditional", "dumpling"],
    canvasData: { version: "6.6.1", background: "#fef2f2", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fef2f2" }),
      R({ left: 0, top: 0, width: 2550, height: 500, fill: "#991b1b" }),
      T("點心", { left: 200, top: 100, width: 400, fontSize: 100, fill: "#fbbf24", fontFamily: "serif" }),
      T("GOLDEN DRAGON", { left: 650, top: 130, width: 1700, fontSize: 64, fontWeight: "bold", fill: "#fef2f2", fontFamily: "Montserrat" }),
      T("DIM SUM HOUSE", { left: 650, top: 240, width: 1700, fontSize: 24, fill: "#fca5a5", fontFamily: "Inter", charSpacing: 300 }),
      T("STEAMED", { left: 200, top: 600, width: 1000, fontSize: 36, fontWeight: "bold", fill: "#991b1b", fontFamily: "Montserrat" }),
      T("Har Gow (shrimp) ......... $6\nSiu Mai (pork) ............... $6\nCheung Fun (rice roll) ..... $7\nXiao Long Bao ............... $8\nChar Siu Bao ................. $5", { left: 200, top: 670, width: 1000, fontSize: 26, fill: "#1f2937", fontFamily: "Inter", lineHeight: 1.7 }),
      T("FRIED & BAKED", { left: 1350, top: 600, width: 1000, fontSize: 36, fontWeight: "bold", fill: "#991b1b", fontFamily: "Montserrat" }),
      T("Spring Rolls (3) ........... $6\nTaro Puffs (3) ............... $7\nEgg Tarts (3) ................. $5\nTurnip Cake .................. $6\nSesame Balls (3) ........... $5", { left: 1350, top: 670, width: 1000, fontSize: 26, fill: "#1f2937", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  {
    name: "Mediterranean Mezze Menu", description: "Warm Mediterranean mezze and grill menu", category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "mediterranean", "mezze", "greek", "middle-eastern"],
    canvasData: { version: "6.6.1", background: "#fffbeb", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fffbeb" }),
      R({ left: 0, top: 0, width: 2550, height: 450, fill: "#1e3a5f" }),
      T("OLIVE & VINE", { left: 200, top: 120, width: 2150, fontSize: 72, fontWeight: "bold", fill: "#fbbf24", textAlign: "center", fontFamily: "Playfair Display" }),
      T("MEDITERRANEAN KITCHEN", { left: 200, top: 260, width: 2150, fontSize: 22, fill: "#93c5fd", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("MEZZE PLATTER", { left: 200, top: 550, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#1e3a5f", fontFamily: "Montserrat" }),
      T("Hummus  ·  Baba Ganoush  ·  Falafel  ·  Tabbouleh\nDolma  ·  Labneh  ·  Muhammara  ·  Pita Bread\nSmall (4 dips) .... $16    Large (8 dips) .... $28", { left: 200, top: 620, width: 2150, fontSize: 26, fill: "#374151", fontFamily: "Inter", lineHeight: 1.7 }),
      T("FROM THE GRILL", { left: 200, top: 880, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#1e3a5f", fontFamily: "Montserrat" }),
      T("Lamb Kofta ............................ $18\nChicken Shawarma .................... $16\nGrilled Halloumi ....................... $14\nMixed Grill Platter .................... $28", { left: 200, top: 950, width: 2150, fontSize: 26, fill: "#374151", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  {
    name: "Juice Bar Menu", description: "Fresh and vibrant juice bar menu", category: "menu", subcategory: "cafe",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "juice", "smoothie", "healthy", "fresh"],
    canvasData: { version: "6.6.1", background: "#ecfdf5", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#ecfdf5" }),
      C({ left: 1900, top: -50, radius: 250, fill: "#34d399", opacity: 0.15 }),
      C({ left: -50, top: 2500, radius: 200, fill: "#fbbf24", opacity: 0.1 }),
      T("FRESH PRESS", { left: 200, top: 200, width: 2150, fontSize: 80, fontWeight: "bold", fill: "#065f46", textAlign: "center", fontFamily: "Montserrat" }),
      T("COLD-PRESSED JUICE BAR", { left: 200, top: 320, width: 2150, fontSize: 22, fill: "#10b981", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("GREEN JUICES", { left: 200, top: 480, width: 1000, fontSize: 32, fontWeight: "bold", fill: "#065f46", fontFamily: "Montserrat" }),
      T("Green Machine ......... $9\nDetox Cleanse ........... $10\nKale Kick .................. $9\nCelery Refresh ........... $8\nSpinach Power ........... $9", { left: 200, top: 550, width: 1000, fontSize: 26, fill: "#1f2937", fontFamily: "Inter", lineHeight: 1.7 }),
      T("FRUIT JUICES", { left: 1350, top: 480, width: 1000, fontSize: 32, fontWeight: "bold", fill: "#065f46", fontFamily: "Montserrat" }),
      T("Tropical Sunrise ........ $8\nBerry Blast ............... $9\nCitrus Glow ............... $8\nWatermelon Mint ........ $8\nMango Tango ............ $9", { left: 1350, top: 550, width: 1000, fontSize: 26, fill: "#1f2937", fontFamily: "Inter", lineHeight: 1.7 }),
      T("SMOOTHIE BOWLS", { left: 200, top: 960, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#065f46", fontFamily: "Montserrat" }),
      T("Acai Bowl ................ $13    Pitaya Bowl .............. $13\nGreen Bowl .............. $12    Protein Bowl ............. $14", { left: 200, top: 1030, width: 2150, fontSize: 26, fill: "#1f2937", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  {
    name: "Korean BBQ Menu", description: "Modern Korean BBQ restaurant menu", category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "korean", "bbq", "grill", "asian"],
    canvasData: { version: "6.6.1", background: "#0f172a", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#0f172a" }),
      T("한국", { left: 200, top: 150, width: 300, fontSize: 80, fill: "#f97316", fontFamily: "serif" }),
      T("SEOUL FIRE", { left: 550, top: 160, width: 1800, fontSize: 72, fontWeight: "bold", fill: "#ffffff", fontFamily: "Montserrat" }),
      T("KOREAN BBQ", { left: 550, top: 280, width: 1800, fontSize: 24, fill: "#f97316", fontFamily: "Inter", charSpacing: 400 }),
      T("GRILL SETS", { left: 200, top: 450, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#f97316", fontFamily: "Montserrat" }),
      T("Bulgogi (marinated beef) ................ $24\nGalbi (short ribs) .......................... $28\nSamgyeopsal (pork belly) ............... $20\nDak Galbi (spicy chicken) ............... $22\nAll sets include rice, banchan, and lettuce wraps", { left: 200, top: 520, width: 2150, fontSize: 26, fill: "#d4d4d4", fontFamily: "Inter", lineHeight: 1.8 }),
      T("STARTERS", { left: 200, top: 880, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#f97316", fontFamily: "Montserrat" }),
      T("Kimchi Jeon (pancake) ................... $10\nMandu (dumplings, 6 pcs) .............. $9\nTteokbokki (rice cakes) .................. $11\nJapchae (glass noodles) ................. $12", { left: 200, top: 950, width: 2150, fontSize: 26, fill: "#d4d4d4", fontFamily: "Inter", lineHeight: 1.8 }),
    ]},
  },
  {
    name: "Tapas Bar Menu", description: "Spanish tapas bar menu with warm tones", category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "tapas", "spanish", "bar", "small-plates"],
    canvasData: { version: "6.6.1", background: "#fef7ed", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fef7ed" }),
      R({ left: 0, top: 0, width: 2550, height: 480, fill: "#9a3412" }),
      T("CASA TAPAS", { left: 200, top: 120, width: 2150, fontSize: 80, fontWeight: "bold", fill: "#fef7ed", textAlign: "center", fontFamily: "Playfair Display" }),
      T("SPANISH SMALL PLATES & WINE", { left: 200, top: 270, width: 2150, fontSize: 22, fill: "#fdba74", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("COLD TAPAS", { left: 200, top: 580, width: 1000, fontSize: 32, fontWeight: "bold", fill: "#9a3412", fontFamily: "Montserrat" }),
      T("Jamón Ibérico ........... $16\nManchego & Olives ..... $10\nGazpacho .................. $8\nPan con Tomate ......... $7\nBoquerones ............... $9", { left: 200, top: 650, width: 1000, fontSize: 26, fill: "#451a03", fontFamily: "Inter", lineHeight: 1.7 }),
      T("HOT TAPAS", { left: 1350, top: 580, width: 1000, fontSize: 32, fontWeight: "bold", fill: "#9a3412", fontFamily: "Montserrat" }),
      T("Patatas Bravas .......... $9\nGambas al Ajillo ......... $14\nCroquetas (4) ............ $10\nPimientos de Padrón ... $8\nTortilla Española ........ $9", { left: 1350, top: 650, width: 1000, fontSize: 26, fill: "#451a03", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  {
    name: "Catering Package Menu", description: "Professional catering services menu", category: "menu", subcategory: "catering",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "catering", "event", "package", "professional"],
    canvasData: { version: "6.6.1", background: "#ffffff", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#ffffff" }),
      R({ left: 0, top: 0, width: 2550, height: 400, fill: "#1e293b" }),
      T("SAVORY & CO.", { left: 200, top: 100, width: 2150, fontSize: 72, fontWeight: "bold", fill: "#ffffff", textAlign: "center", fontFamily: "Montserrat" }),
      T("CATERING SERVICES", { left: 200, top: 230, width: 2150, fontSize: 22, fill: "#94a3b8", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      R({ left: 200, top: 500, width: 700, height: 500, fill: "#f8fafc", rx: 16, ry: 16, stroke: "#e2e8f0", strokeWidth: 1 }),
      T("SILVER", { left: 200, top: 530, width: 700, fontSize: 28, fontWeight: "bold", fill: "#64748b", textAlign: "center", fontFamily: "Montserrat" }),
      T("$25 / person", { left: 200, top: 580, width: 700, fontSize: 22, fill: "#94a3b8", textAlign: "center", fontFamily: "Inter" }),
      T("3 appetizers\n2 entrées\n1 dessert\nBasic setup", { left: 250, top: 640, width: 600, fontSize: 22, fill: "#475569", textAlign: "center", fontFamily: "Inter", lineHeight: 1.6 }),
      R({ left: 925, top: 500, width: 700, height: 500, fill: "#1e293b", rx: 16, ry: 16 }),
      T("GOLD", { left: 925, top: 530, width: 700, fontSize: 28, fontWeight: "bold", fill: "#fbbf24", textAlign: "center", fontFamily: "Montserrat" }),
      T("$45 / person", { left: 925, top: 580, width: 700, fontSize: 22, fill: "#94a3b8", textAlign: "center", fontFamily: "Inter" }),
      T("5 appetizers\n3 entrées\n2 desserts\nFull service + bar", { left: 975, top: 640, width: 600, fontSize: 22, fill: "#e2e8f0", textAlign: "center", fontFamily: "Inter", lineHeight: 1.6 }),
      R({ left: 1650, top: 500, width: 700, height: 500, fill: "#f8fafc", rx: 16, ry: 16, stroke: "#e2e8f0", strokeWidth: 1 }),
      T("PLATINUM", { left: 1650, top: 530, width: 700, fontSize: 28, fontWeight: "bold", fill: "#1e293b", textAlign: "center", fontFamily: "Montserrat" }),
      T("$75 / person", { left: 1650, top: 580, width: 700, fontSize: 22, fill: "#94a3b8", textAlign: "center", fontFamily: "Inter" }),
      T("7 appetizers\n4 entrées\n3 desserts\nPremium service", { left: 1700, top: 640, width: 600, fontSize: 22, fill: "#475569", textAlign: "center", fontFamily: "Inter", lineHeight: 1.6 }),
    ]},
  },
  // 31-36: Final menu templates
  {
    name: "Gastropub Menu", description: "Trendy gastropub menu with craft beer focus", category: "menu", subcategory: "bar",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "gastropub", "craft-beer", "pub", "trendy"],
    canvasData: { version: "6.6.1", background: "#1c1917", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#1c1917" }),
      T("🍺", { left: 1100, top: 100, width: 350, fontSize: 80, textAlign: "center" }),
      T("THE COPPER KETTLE", { left: 200, top: 260, width: 2150, fontSize: 64, fontWeight: "bold", fill: "#d97706", textAlign: "center", fontFamily: "Montserrat" }),
      T("GASTROPUB & CRAFT BREWERY", { left: 200, top: 360, width: 2150, fontSize: 20, fill: "#92400e", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("KITCHEN", { left: 200, top: 500, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#d97706", fontFamily: "Montserrat" }),
      T("Truffle Fries ............................ $10\nBeer-Battered Fish & Chips ......... $16\nSmoked Brisket Sandwich ........... $18\nWild Mushroom Risotto ............... $17\nBurger (wagyu blend) ................. $19", { left: 200, top: 570, width: 2150, fontSize: 26, fill: "#d6d3d1", fontFamily: "Inter", lineHeight: 1.8 }),
      T("ON TAP", { left: 200, top: 950, width: 2150, fontSize: 36, fontWeight: "bold", fill: "#d97706", fontFamily: "Montserrat" }),
      T("House IPA ............... $8    Amber Ale ............... $7\nStout ...................... $8    Wheat Beer .............. $7\nPilsner ................... $7    Seasonal Brew .......... $9", { left: 200, top: 1020, width: 2150, fontSize: 26, fill: "#d6d3d1", fontFamily: "Inter", lineHeight: 1.8 }),
    ]},
  },
  {
    name: "Poke Bowl Menu", description: "Fresh Hawaiian poke bowl menu", category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "poke", "hawaiian", "bowl", "fresh"],
    canvasData: { version: "6.6.1", background: "#f0fdfa", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#f0fdfa" }),
      R({ left: 0, top: 0, width: 2550, height: 450, fill: "#0d9488" }),
      T("ALOHA POKE", { left: 200, top: 120, width: 2150, fontSize: 80, fontWeight: "bold", fill: "#ffffff", textAlign: "center", fontFamily: "Montserrat" }),
      T("BUILD YOUR BOWL", { left: 200, top: 260, width: 2150, fontSize: 24, fill: "#99f6e4", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("1. CHOOSE YOUR BASE", { left: 200, top: 550, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#0d9488", fontFamily: "Montserrat" }),
      T("Sushi Rice  ·  Brown Rice  ·  Mixed Greens  ·  Zoodles", { left: 200, top: 610, width: 2150, fontSize: 26, fill: "#374151", fontFamily: "Inter" }),
      T("2. CHOOSE YOUR PROTEIN", { left: 200, top: 720, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#0d9488", fontFamily: "Montserrat" }),
      T("Ahi Tuna .... $16    Salmon .... $15    Shrimp .... $14    Tofu .... $12", { left: 200, top: 780, width: 2150, fontSize: 26, fill: "#374151", fontFamily: "Inter" }),
      T("3. CHOOSE YOUR TOPPINGS (pick 5)", { left: 200, top: 890, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#0d9488", fontFamily: "Montserrat" }),
      T("Avocado  ·  Mango  ·  Cucumber  ·  Edamame  ·  Seaweed\nCorn  ·  Jalapeño  ·  Crispy Onion  ·  Masago  ·  Sesame Seeds", { left: 200, top: 950, width: 2150, fontSize: 26, fill: "#374151", fontFamily: "Inter", lineHeight: 1.6 }),
    ]},
  },
  {
    name: "Waffle House Menu", description: "Cozy waffle house breakfast menu", category: "menu", subcategory: "brunch",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "waffle", "breakfast", "cozy", "comfort"],
    canvasData: { version: "6.6.1", background: "#fffbeb", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fffbeb" }),
      T("🧇", { left: 1100, top: 80, width: 350, fontSize: 100, textAlign: "center" }),
      T("WAFFLE WONDER", { left: 200, top: 260, width: 2150, fontSize: 72, fontWeight: "bold", fill: "#92400e", textAlign: "center", fontFamily: "Playfair Display" }),
      T("SWEET & SAVORY WAFFLES", { left: 200, top: 370, width: 2150, fontSize: 22, fill: "#b45309", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("SWEET WAFFLES", { left: 200, top: 500, width: 1000, fontSize: 32, fontWeight: "bold", fill: "#92400e", fontFamily: "Montserrat" }),
      T("Classic Butter & Syrup .. $9\nBerries & Cream .......... $12\nBanana Nutella ............ $13\nS'mores Waffle ............ $14\nApple Cinnamon ........... $12\nLemon & Sugar ............ $10", { left: 200, top: 570, width: 1000, fontSize: 26, fill: "#78350f", fontFamily: "Inter", lineHeight: 1.7 }),
      T("SAVORY WAFFLES", { left: 1350, top: 500, width: 1000, fontSize: 32, fontWeight: "bold", fill: "#92400e", fontFamily: "Montserrat" }),
      T("Chicken & Waffle ......... $16\nBacon & Cheese ........... $14\nEgg & Avocado ............ $13\nSmoked Salmon ........... $15\nCaprese Waffle ............ $13\nMushroom & Gruyère .... $14", { left: 1350, top: 570, width: 1000, fontSize: 26, fill: "#78350f", fontFamily: "Inter", lineHeight: 1.7 }),
    ]},
  },
  {
    name: "Smoothie Bar Menu", description: "Tropical smoothie bar menu", category: "menu", subcategory: "cafe",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "smoothie", "tropical", "healthy", "vibrant"],
    canvasData: { version: "6.6.1", background: "#fff1f2", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#fff1f2" }),
      C({ left: 1800, top: 100, radius: 300, fill: "#f43f5e", opacity: 0.08 }),
      C({ left: -100, top: 800, radius: 250, fill: "#f97316", opacity: 0.06 }),
      T("BLEND", { left: 200, top: 200, width: 2150, fontSize: 100, fontWeight: "bold", fill: "#e11d48", textAlign: "center", fontFamily: "Montserrat" }),
      T("SMOOTHIE & JUICE BAR", { left: 200, top: 340, width: 2150, fontSize: 22, fill: "#f43f5e", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("SIGNATURE SMOOTHIES", { left: 200, top: 480, width: 2150, fontSize: 32, fontWeight: "bold", fill: "#e11d48", fontFamily: "Montserrat" }),
      T("Tropical Paradise — mango, pineapple, coconut ............. $9\nBerry Bliss — strawberry, blueberry, banana ................... $8\nGreen Goddess — spinach, banana, almond milk .............. $9\nPeanut Butter Cup — banana, PB, chocolate, oat milk ....... $10\nAcai Energy — acai, granola, honey, mixed berries ........... $11\nMango Lassi — mango, yogurt, cardamom ...................... $8", { left: 200, top: 550, width: 2150, fontSize: 26, fill: "#881337", fontFamily: "Inter", lineHeight: 1.8 }),
    ]},
  },
  {
    name: "Kids Menu", description: "Fun and colorful kids menu", category: "menu", subcategory: "restaurant",
    canvasWidth: 2550, canvasHeight: 3300, tags: ["menu", "kids", "children", "fun", "colorful"],
    canvasData: { version: "6.6.1", background: "#eff6ff", objects: [
      R({ left: 0, top: 0, width: 2550, height: 3300, fill: "#eff6ff" }),
      C({ left: 100, top: 100, radius: 200, fill: "#3b82f6", opacity: 0.1 }),
      C({ left: 2000, top: 200, radius: 180, fill: "#ef4444", opacity: 0.1 }),
      C({ left: 1000, top: 2500, radius: 220, fill: "#22c55e", opacity: 0.08 }),
      T("⭐", { left: 1100, top: 80, width: 350, fontSize: 80, textAlign: "center" }),
      T("KIDS MENU", { left: 200, top: 240, width: 2150, fontSize: 90, fontWeight: "bold", fill: "#1d4ed8", textAlign: "center", fontFamily: "Montserrat" }),
      T("FOR AGES 12 AND UNDER", { left: 200, top: 370, width: 2150, fontSize: 22, fill: "#60a5fa", textAlign: "center", fontFamily: "Inter", charSpacing: 200 }),
      T("🍔 Mini Burger & Fries .............. $7\n🍕 Cheese Pizza Slice ................. $5\n🍗 Chicken Tenders (4 pcs) ......... $7\n🌮 Mini Tacos (3) ....................... $6\n🍝 Mac & Cheese ....................... $6\n🥞 Mini Pancakes ....................... $6", { left: 300, top: 500, width: 1950, fontSize: 30, fill: "#1e3a5f", fontFamily: "Inter", lineHeight: 1.8 }),
      T("ALL MEALS INCLUDE A DRINK & DESSERT", { left: 200, top: 950, width: 2150, fontSize: 22, fontWeight: "bold", fill: "#1d4ed8", textAlign: "center", fontFamily: "Inter" }),
    ]},
  },
];

// ═══════════════════════════════════════════════════════════════
//  INVITATION TEMPLATES (36 designs)
// ═══════════════════════════════════════════════════════════════

export const invitationTemplates = [
  // 1. Classic Wedding Invitation
  {
    name: "Classic Wedding Invitation",
    description: "Elegant classic wedding invitation with serif typography",
    category: "invitation", subcategory: "wedding",
    canvasWidth: 2100, canvasHeight: 2800,
    tags: ["invitation", "wedding", "classic", "elegant", "serif"],
    canvasData: { version: "6.6.1", background: "#faf8f5", objects: [
      R({ left: 0, top: 0, width: 2100, height: 2800, fill: "#faf8f5" }),
      R({ left: 80, top: 80, width: 1940, height: 2640, fill: "transparent", stroke: "#c9a84c", strokeWidth: 2 }),
      R({ left: 100, top: 100, width: 1900, height: 2600, fill: "transparent", stroke: "#c9a84c", strokeWidth: 1 }),
      T("Together with their families", { left: 200, top: 300, width: 1700, fontSize: 24, fill: "#8a7a60", textAlign: "center", fontFamily: "Inter", fontStyle: "italic" }),
      T("Sarah Elizabeth", { left: 200, top: 420, width: 1700, fontSize: 72, fill: "#2c2c2c", textAlign: "center", fontFamily: "Playfair Display", fontStyle: "italic" }),
      T("&", { left: 200, top: 530, width: 1700, fontSize: 60, fill: "#c9a84c", textAlign: "center", fontFamily: "Playfair Display" }),
      T("James William", { left: 200, top: 620, width: 1700, fontSize: 72, fill: "#2c2c2c", textAlign: "center", fontFamily: "Playfair Display", fontStyle: "italic" }),
      T("request the pleasure of your company\nat the celebration of their marriage", { left: 200, top: 780, width: 1700, fontSize: 22, fill: "#8a7a60", textAlign: "center", fontFamily: "Inter", lineHeight: 1.6 }),
      R({ left: 900, top: 880, width: 300, height: 2, fill: "#c9a84c" }),
      T("Saturday, the Twenty-First of June\nTwo Thousand Twenty-Six\nat Four O'Clock in the Afternoon", { left: 200, top: 930, width: 1700, fontSize: 26, fill: "#2c2c2c", textAlign: "center", fontFamily: "Playfair Display", lineHeight: 1.6 }),
      T("The Grand Ballroom\n123 Elegant Avenue, New York", { left: 200, top: 1120, width: 1700, fontSize: 22, fill: "#8a7a60", textAlign: "center", fontFamily: "Inter", lineHeight: 1.5 }),
      T("Reception to follow", { left: 200, top: 1250, width: 1700, fontSize: 20, fill: "#c9a84c", textAlign: "center", fontFamily: "Inter", fontStyle: "italic" }),
      T("RSVP by May 15, 2026", { left: 200, top: 1350, width: 1700, fontSize: 20, fill: "#8a7a60", textAlign: "center", fontFamily: "Inter" }),
    ]},
  },
  // 2. Modern Minimalist Wedding
  {
    name: "Modern Minimalist Wedding",
    description: "Clean modern wedding invitation with minimal design",
    category: "invitation", subcategory: "wedding",
    canvasWidth: 2100, canvasHeight: 2800,
    tags: ["invitation", "wedding", "modern", "minimalist", "clean"],
    canvasData: { version: "6.6.1", background: "#ffffff", objects: [
      R({ left: 0, top: 0, width: 2100, height: 2800, fill: "#ffffff" }),
      R({ left: 0, top: 0, width: 8, height: 2800, fill: "#1a1a1a" }),
      T("06.21.26", { left: 200, top: 300, width: 1700, fontSize: 20, fill: "#999999", fontFamily: "Inter", charSpacing: 400 }),
      T("SARAH\n&\nJAMES", { left: 200, top: 500, width: 1700, fontSize: 100, fontWeight: "bold", fill: "#1a1a1a", fontFamily: "Montserrat", lineHeight: 1.1 }),
      R({ left: 200, top: 900, width: 100, height: 3, fill: "#1a1a1a" }),
      T("ARE GETTING MARRIED", { left: 200, top: 960, width: 1700, fontSize: 18, fill: "#999999", fontFamily: "Inter", charSpacing: 400 }),
      T("JUNE 21, 2026  ·  4:00 PM\nTHE MODERN GALLERY\nNEW YORK CITY", { left: 200, top: 1100, width: 1700, fontSize: 24, fill: "#1a1a1a", fontFamily: "Inter", lineHeight: 1.8 }),
      T("RSVP  ·  sarah-and-james.com", { left: 200, top: 1350, width: 1700, fontSize: 18, fill: "#999999", fontFamily: "Inter", charSpacing: 200 }),
    ]},
  },
  // 3. Floral Wedding Invitation
  {
    name: "Floral Garden Wedding",
    description: "Romantic floral wedding invitation with watercolor feel",
    category: "invitation", subcategory: "wedding",
    canvasWidth: 2100, canvasHeight: 2800,
    tags: ["invitation", "wedding", "floral", "romantic", "garden"],
    canvasData: { version: "6.6.1", background: "#fdf2f8", objects: [
      R({ left: 0, top: 0, width: 2100, height: 2800, fill: "#fdf2f8" }),
      C({ left: -100, top: -100, radius: 300, fill: "#f9a8d4", opacity: 0.2 }),
      C({ left: 1700, top: -50, radius: 250, fill: "#c084fc", opacity: 0.15 }),
      C({ left: 1600, top: 2300, radius: 280, fill: "#f9a8d4", opacity: 0.15 }),
      C({ left: -50, top: 2400, radius: 200, fill: "#86efac", opacity: 0.15 }),
      T("You're Invited", { left: 200, top: 400, width: 1700, fontSize: 28, fill: "#9d174d", textAlign: "center", fontFamily: "Inter", fontStyle: "italic" }),
      T("Sarah & James", { left: 200, top: 500, width: 1700, fontSize: 80, fill: "#831843", textAlign: "center", fontFamily: "Playfair Display", fontStyle: "italic" }),
      T("are tying the knot!", { left: 200, top: 630, width: 1700, fontSize: 24, fill: "#be185d", textAlign: "center", fontFamily: "Inter", fontStyle: "italic" }),
      R({ left: 900, top: 720, width: 300, height: 2, fill: "#ec4899" }),
      T("June 21, 2026\nFour in the Afternoon\nRose Garden Estate\nSan Francisco, CA", { left: 200, top: 800, width: 1700, fontSize: 28, fill: "#831843", textAlign: "center", fontFamily: "Playfair Display", lineHeight: 1.6 }),
      T("Dinner & Dancing to Follow", { left: 200, top: 1060, width: 1700, fontSize: 20, fill: "#ec4899", textAlign: "center", fontFamily: "Inter" }),
      T("RSVP by May 15  ·  sarah-james.rsvp.com", { left: 200, top: 1150, width: 1700, fontSize: 18, fill: "#9d174d", textAlign: "center", fontFamily: "Inter" }),
    ]},
  },
  // 4. Birthday Party - Kids
  {
    name: "Kids Birthday Party",
    description: "Fun colorful kids birthday party invitation",
    category: "invitation", subcategory: "birthday",
    canvasWidth: 2100, canvasHeight: 2800,
    tags: ["invitation", "birthday", "kids", "party", "colorful", "fun"],
    canvasData: { version: "6.6.1", background: "#eff6ff", objects: [
      R({ left: 0, top: 0, width: 2100, height: 2800, fill: "#eff6ff" }),
      C({ left: 100, top: 100, radius: 150, fill: "#3b82f6", opacity: 0.15 }),
      C({ left: 1600, top: 200, radius: 180, fill: "#ef4444", opacity: 0.12 }),
      C({ left: 800, top: 2200, radius: 200, fill: "#22c55e", opacity: 0.1 }),
      C({ left: 1700, top: 2000, radius: 130, fill: "#f59e0b", opacity: 0.15 }),
      T("🎈🎉🎂", { left: 200, top: 200, width: 1700, fontSize: 80, textAlign: "center" }),
      T("YOU'RE INVITED TO", { left: 200, top: 400, width: 1700, fontSize: 24, fill: "#3b82f6", textAlign: "center", fontFamily: "Inter", charSpacing: 300 }),
      T("Emma's\n7th Birthday!", { left: 200, top: 470, width: 1700, fontSize: 72, fontWeight: "bold", fill: "#1e40af", textAlign: "center", fontFamily: "Montserrat", lineHeight: 1.2 }),
      R({ left: 800, top: 700, width: 500, height: 4, fill: "#3b82f6" }),
      T("Saturday, April 12, 2026\n2:00 PM - 5:00 PM", { left: 200, top: 770, width: 1700, fontSize: 28, fill: "#1e3a5f", textAlign: "center", fontFamily: "Inter", lineHeight: 1.5 }),
      T("FUN ZONE ADVENTURE PARK\n456 Play Street, Anytown", { left: 200, top: 900, width: 1700, fontSize: 24, fill: "#64748b", textAlign: "center", fontFamily: "Inter", lineHeight: 1.5 }),
      R({ left: 600, top: 1030, width: 900, height: 80, fill: "#3b82f6", rx: 40, ry: 40 }),
      T("Games · Cake · Prizes!", { left: 600, top: 1050, width: 900, fontSize: 24, fontWeight: "bold", fill: "#ffffff", textAlign: "center", fontFamily: "Inter" }),
      T("RSVP to Mom: (555) 123-4567", { left: 200, top: 1180, width: 1700, fontSize: 20, fill: "#64748b", textAlign: "center", fontFamily: "Inter" }),
    ]},
  },
  // 5. Elegant Birthday
  {
    name: "Elegant Birthday Dinner",
    description: "Sophisticated adult birthday dinner invitation",
    category: "invitation", subcategory: "birthday",
    canvasWidth: 2100, canvasHeight: 2800,
    tags: ["invitation", "birthday", "elegant", "dinner", "adult"],
    canvasData: { version: "6.6.1", background: "#0f172a", objects: [
      R({ left: 0, top: 0, width: 2100, height: 2800, fill: "#0f172a" }),
      R({ left: 80, top: 80, width: 1940, height: 2640, fill: "transparent", stroke: "#c9a84c", strokeWidth: 1 }),
      T("YOU ARE CORDIALLY INVITED", { left: 200, top: 400, width: 1700, fontSize: 18, fill: "#c9a84c", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      T("Celebrating", { left: 200, top: 500, width: 1700, fontSize: 32, fill: "#94a3b8", textAlign: "center", fontFamily: "Playfair Display", fontStyle: "italic" }),
      T("50", { left: 200, top: 580, width: 1700, fontSize: 160, fontWeight: "bold", fill: "#c9a84c", textAlign: "center", fontFamily: "Montserrat" }),
      T("YEARS OF MICHAEL", { left: 200, top: 780, width: 1700, fontSize: 28, fill: "#ffffff", textAlign: "center", fontFamily: "Montserrat", charSpacing: 300 }),
      R({ left: 900, top: 870, width: 300, height: 2, fill: "#c9a84c" }),
      T("Saturday, March 15, 2026\nSeven O'Clock in the Evening\nThe Ritz-Carlton\nBlack Tie Optional", { left: 200, top: 930, width: 1700, fontSize: 24, fill: "#94a3b8", textAlign: "center", fontFamily: "Inter", lineHeight: 1.7 }),
      T("RSVP by March 1", { left: 200, top: 1200, width: 1700, fontSize: 18, fill: "#c9a84c", textAlign: "center", fontFamily: "Inter" }),
    ]},
  },
  // 6. Baby Shower
  {
    name: "Baby Shower - Pastel",
    description: "Soft pastel baby shower invitation",
    category: "invitation", subcategory: "baby-shower",
    canvasWidth: 2100, canvasHeight: 2800,
    tags: ["invitation", "baby-shower", "pastel", "soft", "baby"],
    canvasData: { version: "6.6.1", background: "#fefce8", objects: [
      R({ left: 0, top: 0, width: 2100, height: 2800, fill: "#fefce8" }),
      C({ left: 100, top: 100, radius: 200, fill: "#fde68a", opacity: 0.3 }),
      C({ left: 1600, top: 200, radius: 180, fill: "#a7f3d0", opacity: 0.3 }),
      C({ left: 900, top: 2200, radius: 250, fill: "#fbcfe8", opacity: 0.2 }),
      T("👶", { left: 900, top: 250, width: 300, fontSize: 80, textAlign: "center" }),
      T("BABY SHOWER", { left: 200, top: 420, width: 1700, fontSize: 20, fill: "#92400e", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      T("Oh Baby!", { left: 200, top: 490, width: 1700, fontSize: 72, fill: "#92400e", textAlign: "center", fontFamily: "Playfair Display", fontStyle: "italic" }),
      T("Please join us in celebrating\nthe upcoming arrival of", { left: 200, top: 620, width: 1700, fontSize: 24, fill: "#78350f", textAlign: "center", fontFamily: "Inter", lineHeight: 1.5 }),
      T("Baby Thompson", { left: 200, top: 730, width: 1700, fontSize: 48, fontWeight: "bold", fill: "#92400e", textAlign: "center", fontFamily: "Playfair Display" }),
      R({ left: 900, top: 830, width: 300, height: 2, fill: "#f59e0b" }),
      T("Saturday, May 10, 2026\n2:00 PM\n789 Sunshine Lane", { left: 200, top: 890, width: 1700, fontSize: 26, fill: "#78350f", textAlign: "center", fontFamily: "Inter", lineHeight: 1.6 }),
      T("Hosted by Emily & Grace", { left: 200, top: 1080, width: 1700, fontSize: 20, fill: "#b45309", textAlign: "center", fontFamily: "Inter", fontStyle: "italic" }),
      T("RSVP: (555) 987-6543", { left: 200, top: 1150, width: 1700, fontSize: 18, fill: "#92400e", textAlign: "center", fontFamily: "Inter" }),
    ]},
  },
  // 7. Graduation Party
  {
    name: "Graduation Celebration",
    description: "Bold graduation party invitation",
    category: "invitation", subcategory: "graduation",
    canvasWidth: 2100, canvasHeight: 2800,
    tags: ["invitation", "graduation", "celebration", "academic", "bold"],
    canvasData: { version: "6.6.1", background: "#1e293b", objects: [
      R({ left: 0, top: 0, width: 2100, height: 2800, fill: "#1e293b" }),
      T("🎓", { left: 900, top: 200, width: 300, fontSize: 100, textAlign: "center" }),
      T("CLASS OF 2026", { left: 200, top: 400, width: 1700, fontSize: 24, fill: "#fbbf24", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      T("GRADUATION\nPARTY", { left: 200, top: 470, width: 1700, fontSize: 80, fontWeight: "bold", fill: "#ffffff", textAlign: "center", fontFamily: "Montserrat", lineHeight: 1.1 }),
      R({ left: 900, top: 710, width: 300, height: 3, fill: "#fbbf24" }),
      T("Join us in celebrating", { left: 200, top: 770, width: 1700, fontSize: 22, fill: "#94a3b8", textAlign: "center", fontFamily: "Inter", fontStyle: "italic" }),
      T("ALEX JOHNSON", { left: 200, top: 830, width: 1700, fontSize: 48, fontWeight: "bold", fill: "#fbbf24", textAlign: "center", fontFamily: "Montserrat" }),
      T("Bachelor of Science, Computer Engineering\nStanford University", { left: 200, top: 920, width: 1700, fontSize: 22, fill: "#94a3b8", textAlign: "center", fontFamily: "Inter", lineHeight: 1.5 }),
      T("Saturday, June 14, 2026\n5:00 PM - 10:00 PM\nThe Johnson Residence\n321 Oak Drive, Palo Alto", { left: 200, top: 1060, width: 1700, fontSize: 24, fill: "#e2e8f0", textAlign: "center", fontFamily: "Inter", lineHeight: 1.6 }),
      T("RSVP by June 1  ·  alex-grad.com", { left: 200, top: 1300, width: 1700, fontSize: 18, fill: "#fbbf24", textAlign: "center", fontFamily: "Inter" }),
    ]},
  },
  // 8. Corporate Event
  {
    name: "Corporate Gala Invitation",
    description: "Professional corporate gala event invitation",
    category: "invitation", subcategory: "corporate",
    canvasWidth: 2100, canvasHeight: 2800,
    tags: ["invitation", "corporate", "gala", "professional", "business"],
    canvasData: { version: "6.6.1", background: "#0a0a0a", objects: [
      R({ left: 0, top: 0, width: 2100, height: 2800, fill: "#0a0a0a" }),
      R({ left: 60, top: 60, width: 1980, height: 2680, fill: "transparent", stroke: "#374151", strokeWidth: 1 }),
      T("ACME CORPORATION", { left: 200, top: 300, width: 1700, fontSize: 20, fill: "#6b7280", textAlign: "center", fontFamily: "Inter", charSpacing: 400 }),
      T("ANNUAL GALA", { left: 200, top: 400, width: 1700, fontSize: 72, fontWeight: "bold", fill: "#ffffff", textAlign: "center", fontFamily: "Montserrat" }),
      T("2026", { left: 200, top: 510, width: 1700, fontSize: 48, fontWeight: "300", fill: "#6366f1", textAlign: "center", fontFamily: "Inter" }),
      R({ left: 900, top: 610, width: 300, height: 2, fill: "#6366f1" }),
      T("You are cordially invited to join us\nfor an evening of celebration and networking", { left: 200, top: 670, width: 1700, fontSize: 22, fill: "#9ca3af", textAlign: "center", fontFamily: "Inter", lineHeight: 1.6 }),
      T("December 12, 2026\n7:00 PM\nThe Grand Hotel Ballroom\nFormal Attire", { left: 200, top: 830, width: 1700, fontSize: 26, fill: "#e5e7eb", textAlign: "center", fontFamily: "Inter", lineHeight: 1.7 }),
      R({ left: 700, top: 1080, width: 700, height: 60, fill: "#6366f1", rx: 30, ry: 30 }),
      T("RSVP BY NOV 30", { left: 700, top: 1095, width: 700, fontSize: 18, fontWeight: "bold", fill: "#ffffff", textAlign: "center", fontFamily: "Inter" }),
    ]},
  },
  // 9-18: More invitation types
  {
    name: "Holiday Party Invitation", description: "Festive holiday party invitation", category: "invitation", subcategory: "holiday",
    canvasWidth: 2100, canvasHeight: 2800, tags: ["invitation", "holiday", "christmas", "festive", "party"],
    canvasData: { version: "6.6.1", background: "#14532d", objects: [
      R({ left: 0, top: 0, width: 2100, height: 2800, fill: "#14532d" }),
      C({ left: 100
